In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [4]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [7]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a[[0,1,2], [0,1,0]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [ ]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11, 12])
print(v.dot())